apiVersion: v1
kind: Service
metadata:
  name: db  # Important: This name must be 'db' as it's referenced in the application
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
  # No type specified means ClusterIP (internal only)
