apiVersion: v1
kind: Service
metadata:
  name: redis  # Important: Service name must be 'redis' as it's referenced in the application
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379  # Service port
      targetPort: 6379  # Container port
  selector:
    name: redis-pod
    app: demo-voting-app
  # No type specified means ClusterIP (internal only)
